---
# Check for rvm. Do not proceed if we find it.
- include_tasks: rvm_check.yml

# Setup and define facts.
- include_tasks: setup.yml

# Install rbenv.
- include_tasks: rbenv_install.yml

# Install rbenv plugins.
- include_tasks: rbenv_plugins.yml

# Setup default-gems plugin if it was installed.
- include_tasks: default_gems_plugin.yml
  when: "'rbenv-default-gems' in rbenv_installed_plugins.stdout"

# Use ruby-build plugin to install ruby versions if it was installed.
#
# Looping over an included task file allows the task file to be simpler.
- include_tasks: ruby_build_plugin.yml
  vars:
    version: "{{ ruby_build_version }}"
  when: "'ruby-build' in rbenv_installed_plugins.stdout"
  loop: "{{ rbenv_ruby_build_versions }}"
  loop_control:
    loop_var: ruby_build_version
