---
- name: Clone rbenv repository for each user.
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "{{ rbenv_user_install_dir }}"
    update: true
    accept_hostkey: true
    version: "{{ rbenv_version }}"

- name: Set permissions on newly cloned rbenv repos and contents.
  file:
    path: "{{ rbenv_user_install_dir }}"
    owner: "{{ rbenv_user.name }}"
    group: "{{ rbenv_user.group }}"
    recurse: true
  changed_when: false

- name: Compile dynamic bash extension to speed up rbenv.
  block:
    - name: Check for the existence of a Makefile.
      stat:
        path: "{{ rbenv_user_install_dir }}/src/Makefile"
      register: rbenv_makefile
      when: rbenv_use_bash_extension

    - name: Configure rbenv dynamic bash extension for each user.
      command: "src/configure"
      args:
        chdir: "{{ rbenv_user_install_dir }}"
      become: true
      become_user: "{{ rbenv_user.name }}"
      when:
        - rbenv_use_bash_extension
        - not rbenv_makefile.stat.exists

    # @todo: Figure out how to tell if this should actually be run.
    - name: Make rbenv dynamic bash extension for each user.
      command: "make -C ./src"
      args:
        chdir: "{{ rbenv_user_install_dir }}"
      become: true
      become_user: "{{ rbenv_user.name }}"
      when: rbenv_use_bash_extension
      changed_when: false

- name: Add rbenv bin path to $PATH.
  block:
    - name: Add rbenv bin path to bash or zsh $PATH.
      lineinfile:
        dest: "{{ rbenv_user_home_dir }}/{{ rbenv_profile_file }}"
        line: "{{ command_line }}"
      loop:
        - "{{ rbenv_shell_export_command }}"
        - "{{ rbenv_shell_init_command }}"
      loop_control:
        loop_var: command_line
      when:
        - rbenv_update_path
        - "'fish' not in rbenv_user_shell.stdout"

    - name: Add rbenv bin path to fish $PATH.
      shell: "{{ rbenv_fish_export_command }}"
      args:
        executable: "{{ rbenv_user_shell.stdout }}"
      become: true
      become_user: "{{ rbenv_user.name }}"
      when:
        - rbenv_update_path
        - "'fish' in rbenv_user_shell.stdout"
      changed_when: false

    - name: Make sure fish shell loads rbenv automatically.
      lineinfile:
        path: "{{ rbenv_user_home_dir }}/{{ rbenv_fish_profile_file }}"
        line: "{{ rbenv_fish_init_command }}"
        create: true
        owner: "{{ rbenv_user.name }}"
        group: "{{ rbenv_user.group }}"
      when:
        - rbenv_update_path
        - "'fish' in rbenv_user_shell.stdout"
      changed_when: false
