---
- name: Converge
  hosts: all

  vars:
    users:
      - name: "lorem"
        group: "lorem"
        shell: "/bin/bash"
        ruby_versions:
          - 2.4.1
          - 2.5.1
      - name: "ipsum"
        group: "ipsum"
        shell: "/usr/bin/fish"
        ruby_versions:
          - 2.4.1

  pre_tasks:
    - name: Install required packages.
      apt:
        name: "{{ package }}"
      loop:
        - "curl"
        - "fish"
        - "gcc"
        - "git"
        - "libssl-dev"
        - "libreadline-dev"
        - "make"
        - "zlib1g-dev"
      loop_control:
        loop_var: package

    - name: Create users.
      user:
        name: "{{ user.name }}"
        shell: "{{ user.shell }}"
      loop: "{{ users }}"
      loop_control:
        loop_var: user

  tasks:
    - include_role:
        name: ansible-role-rbenv
      vars:
        rbenv_user: "{{ user }}"
        rbenv_ruby_build_versions: "{{ user.ruby_versions }}"
      loop: "{{ users }}"
      loop_control:
        loop_var: user
